### ISSUE TITLE
paso a paso

### ISSUE THREAD

**Issue by raular4322** [davidmss2000/HITO-3#1]
Primero en las rutas, los requiere tienen que ser literalmente las primeras lineas del fichero, siempre
tampoco estas usando express, y seria interesante porque es el sistema que te permite trabajar con http y sistemas de rutas
y yo pondria los app.metodo fuera del export, y luego pones module.exports = app; porque la legibilidad es lo mas importante, por encima de si hacerlo como tu ahorra 5 instrucciones de procesador, que no lo se XD

En el modelo, no fuerzas que phone sea de 9 caracteres de longitud, y eso lo pedí expresamente, y email no lo haces unico

En el controlador, lo mas importante es que hay formas mas eficientes de validar los campos y de como poner el codigo en general, pero eso ya lo verás, pero algo que te tienes que quitar cuanto antes es ese estilo de return, en vez de ponerlo al final, ponlo una linea mas arriba, me explico:

// mal
res.status.send({})
return

// bien
return res.status.send({})

y ahora el server.js, de nuevo, los requiere arriba siempre, y mejor mete el app.listen dentro de la conexion a mongo, porque si la base de datos peta no quieres que la api escuche nada, quieres que se apague todo mientras corriges cosas

es to largo, pero en general está bien, buen trabajo

**Comment by davidmss2000** [comment]
Ya lo he corregido, si no te importa cuando tengas tiempo míratelo y dime si hay algo mal.
